yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from .import views


app_name = 'posts'

urlpatterns = [

    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),

]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                       PasswordResetView,
                                       )
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(),
         name='signup',
         ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_change/', PasswordChangeView.as_view(),
         name='password_change_form',
         ),
    path('password_change/done/', PasswordChangeDoneView.as_view(),
         name='password_change_done',
         ),
    path('password_reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset',
         ),
    path('password_reset/confirm/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',
         ),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete',
         ),
    path('password_reset/', PasswordResetView.as_view(),
         name='password_reset_form',
         ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст Поста',
        help_text='Текст нового поста')
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )

    group = models.ForeignKey(
        Group,
        help_text='Группа, к которой будет относиться пост',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
    )

    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение',
        }
        help_texts = {
            'text': 'Введите текст поста.',
            'group': 'Введите название группы.',
            'image': 'Загрузите изображение.',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')
        help_texts = {'username': "Обязательно. Не более 30 символов\n"
                      "Буквы, цифры и символы"}
        labels = {'first_name': "Имя",
                  'last_name': "Фамилия",
                  'username': "Имя пользователя",
                  'email': "Email",
                  'password1': "Пароль",
                  'password2': "Подтверждение пароля"}

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def csrf_failure(request, reason=""):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from .utils import get_page_context
from .models import Group, Post, User
from .forms import PostForm
from django.conf import settings


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    context = {
        'page_obj': get_page_context(post_list, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    context = {
        'group': group,
        'page_obj': get_page_context(post_list, request),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.prefetch_related('group')
    post_count = author.posts.count()
    context = {
        'author': author,
        'page_obj': get_page_context(post_list, request),
        'post_count': post_count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related
                             ('author', 'group'), pk=post_id)
    title = post.text[:settings.TEXT_TITLE]
    context = {
        'post': post,
        'title': title,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    form = PostForm(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post.pk)
    context = {'form': form,
               'is_edit': is_edit,
               }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, меня зовут Акоб</h1>
<p>
    Я автор данного ресурса
</p>
    <p>
    Ты можешь поддержать меня и подписаться на мой <a href="https://github.com/AkobArm" title=>GitHub</a>
    </p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Стек сайта</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Тут ты видишь на чем я делал сайт.</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
 <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}   
    </footer>
  </body>

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
    <h1>Кастомный CSRF check error. 403</h1>
    <p>А вот это ты зря сделал, за тобой уже выехали. БЕГИ</p>
{% endblock %}

yatube/templates/includes/footer.html
  <div class="border-top text-center py-3"> 
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </div>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link {% if request.resolver_match.view_name  == 'about:author' %}
        active
      {% endif %}" href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.view_name  == 'about:tech' %}
        active
      {% endif %}" href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if request.resolver_match.view_name  == 'posts:post_create' %}
        active
      {% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if request.resolver_match.view_name  == 'password_change' %}
        active
      {% endif %}" href="{% url 'password_change' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if request.resolver_match.view_name  == 'logout' %}
        active
      {% endif %}" href="{% url 'logout' %}">Выйти</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      <li>
        {% else %}
      <li class="nav-item"> 
        <a class="nav-link {% if request.resolver_match.view_name  == 'users:login' %}
        active
      {% endif %}" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if request.resolver_match.view_name  == 'users:signup' %}
        active
      {% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>      

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">      
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}            
          </div>
          <div class="card-body">
            {% load user_filters %}
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
            <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества: {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
{% for post in page_obj %} 
  <li>Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
<br /> 
<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последнее обновление на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Последнее обновление на сайте</h1>
  {% for post in page_obj %}
  <ul>
    <li>Автор: {{ post.author.get_full_name }}</li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>      
     <p>{{ post.text }}</p>
  {% if post.group is not None %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {%endif%}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
    <main>
        <div class="container py-5">
            <div class="row">
                <aside class="col-12 col-md-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            Дата публикации: {{ post.pub_date|date:"j E Y" }}
                        </li>
                        {% if post.group %}
                            <li class="list-group-item">
                            Группа: <a>{{ post.group.title }}</a>
                            <a href="{% url 'posts:group_list' post.group.slug %}">
                                все записи группы
                            </a>
                        {% endif %}
                        </li>
                        <li class="list-group-item">
                            Автор: {{ post.author.get_full_name }}
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Всего постов автора: {{ post.author.posts.count }}
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                            </a>
                        </li>
                    </ul>
                </aside>
                <article>
                    <ul>
                        <li>
                            Автор: {{ post.author.get_full_name }}
                            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                        </li>
                    </ul>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                    <p>{{ post.text }}</p>
                    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
                </article>
            </div>
    </main>
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профиль пользователя {{ autgor.get_full_name }}
{% endblock %} 
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  {% for post in page_obj %}   
  <article>
    <ul>
      <li>
        Автор: {{ author.username }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"j E Y" }}
      </li>
    </ul>
    <p>
      {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    <br /> 
    {% if post.group %}       
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> 
      </div> 
    </div> 
</div> 
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body">
          <p>Пароль изменён успешно</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_change_form' %}">
          {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}
{{ auth:password_reset }}
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> 
    </div> 
  </div> 
</div> 
{% endif %}

{% endblock %} 

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a class="btn btn-primary" href="{% url 'users:login' %}">Войти</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_reset_form' %}">
          {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %} 